/* This file ist generated by the program DSLMethodsGenerator. DO NOT EDIT IT MANUALLY! */

namespace BlazorDSL {
    public static partial class Html {
        
            public static Attribute abbr(string value)
                => new Attribute("abbr", value);

            public static Attribute accept(string value)
                => new Attribute("accept", value);

            public static Attribute acceptCharset(string value)
                => new Attribute("accept-charset", value);

            public static Attribute accesskey(string value)
                => new Attribute("accesskey", value);

            public static Attribute action(string value)
                => new Attribute("action", value);

            public static Attribute allow(string value)
                => new Attribute("allow", value);

            public static Attribute allowfullscreen(string value)
                => new Attribute("allowfullscreen", value);

            public static Attribute alt(string value)
                => new Attribute("alt", value);

            public static Attribute @as(string value)
                => new Attribute("as", value);

            public static Attribute async(string value)
                => new Attribute("async", value);

            public static Attribute autocapitalize(string value)
                => new Attribute("autocapitalize", value);

            public static Attribute autocomplete(string value)
                => new Attribute("autocomplete", value);

            public static Attribute autofocus(string value)
                => new Attribute("autofocus", value);

            public static Attribute autoplay(string value)
                => new Attribute("autoplay", value);

            public static Attribute charset(string value)
                => new Attribute("charset", value);

            public static Attribute @checked(string value)
                => new Attribute("checked", value);

            public static Attribute cite(string value)
                => new Attribute("cite", value);

            public static Attribute className(string value)
                => new Attribute("class", value);

            public static Attribute color(string value)
                => new Attribute("color", value);

            public static Attribute cols(string value)
                => new Attribute("cols", value);

            public static Attribute colspan(string value)
                => new Attribute("colspan", value);

            public static Attribute content(string value)
                => new Attribute("content", value);

            public static Attribute contenteditable(string value)
                => new Attribute("contenteditable", value);

            public static Attribute controls(string value)
                => new Attribute("controls", value);

            public static Attribute coords(string value)
                => new Attribute("coords", value);

            public static Attribute crossorigin(string value)
                => new Attribute("crossorigin", value);

            public static Attribute data(string value)
                => new Attribute("data", value);

            public static Attribute datetime(string value)
                => new Attribute("datetime", value);

            public static Attribute decoding(string value)
                => new Attribute("decoding", value);

            public static Attribute @default(string value)
                => new Attribute("default", value);

            public static Attribute defer(string value)
                => new Attribute("defer", value);

            public static Attribute dir(string value)
                => new Attribute("dir", value);

            public static Attribute dirname(string value)
                => new Attribute("dirname", value);

            public static Attribute disabled(string value)
                => new Attribute("disabled", value);

            public static Attribute download(string value)
                => new Attribute("download", value);

            public static Attribute draggable(string value)
                => new Attribute("draggable", value);

            public static Attribute enctype(string value)
                => new Attribute("enctype", value);

            public static Attribute enterkeyhint(string value)
                => new Attribute("enterkeyhint", value);

            public static Attribute @for(string value)
                => new Attribute("for", value);

            public static Attribute form(string value)
                => new Attribute("form", value);

            public static Attribute formaction(string value)
                => new Attribute("formaction", value);

            public static Attribute formenctype(string value)
                => new Attribute("formenctype", value);

            public static Attribute formmethod(string value)
                => new Attribute("formmethod", value);

            public static Attribute formnovalidate(string value)
                => new Attribute("formnovalidate", value);

            public static Attribute formtarget(string value)
                => new Attribute("formtarget", value);

            public static Attribute headers(string value)
                => new Attribute("headers", value);

            public static Attribute height(string value)
                => new Attribute("height", value);

            public static Attribute hidden(string value)
                => new Attribute("hidden", value);

            public static Attribute high(string value)
                => new Attribute("high", value);

            public static Attribute href(string value)
                => new Attribute("href", value);

            public static Attribute hreflang(string value)
                => new Attribute("hreflang", value);

            public static Attribute httpEquiv(string value)
                => new Attribute("http-equiv", value);

            public static Attribute id(string value)
                => new Attribute("id", value);

            public static Attribute imagesizes(string value)
                => new Attribute("imagesizes", value);

            public static Attribute imagesrcset(string value)
                => new Attribute("imagesrcset", value);

            public static Attribute inputmode(string value)
                => new Attribute("inputmode", value);

            public static Attribute integrity(string value)
                => new Attribute("integrity", value);

            public static Attribute @is(string value)
                => new Attribute("is", value);

            public static Attribute ismap(string value)
                => new Attribute("ismap", value);

            public static Attribute itemid(string value)
                => new Attribute("itemid", value);

            public static Attribute itemprop(string value)
                => new Attribute("itemprop", value);

            public static Attribute itemref(string value)
                => new Attribute("itemref", value);

            public static Attribute itemscope(string value)
                => new Attribute("itemscope", value);

            public static Attribute itemtype(string value)
                => new Attribute("itemtype", value);

            public static Attribute kind(string value)
                => new Attribute("kind", value);

            public static Attribute label(string value)
                => new Attribute("label", value);

            public static Attribute lang(string value)
                => new Attribute("lang", value);

            public static Attribute list(string value)
                => new Attribute("list", value);

            public static Attribute loading(string value)
                => new Attribute("loading", value);

            public static Attribute loop(string value)
                => new Attribute("loop", value);

            public static Attribute low(string value)
                => new Attribute("low", value);

            public static Attribute max(string value)
                => new Attribute("max", value);

            public static Attribute maxlength(string value)
                => new Attribute("maxlength", value);

            public static Attribute media(string value)
                => new Attribute("media", value);

            public static Attribute method(string value)
                => new Attribute("method", value);

            public static Attribute min(string value)
                => new Attribute("min", value);

            public static Attribute minlength(string value)
                => new Attribute("minlength", value);

            public static Attribute multiple(string value)
                => new Attribute("multiple", value);

            public static Attribute muted(string value)
                => new Attribute("muted", value);

            public static Attribute name(string value)
                => new Attribute("name", value);

            public static Attribute nomodule(string value)
                => new Attribute("nomodule", value);

            public static Attribute nonce(string value)
                => new Attribute("nonce", value);

            public static Attribute novalidate(string value)
                => new Attribute("novalidate", value);

            public static Attribute open(string value)
                => new Attribute("open", value);

            public static Attribute optimum(string value)
                => new Attribute("optimum", value);

            public static Attribute pattern(string value)
                => new Attribute("pattern", value);

            public static Attribute ping(string value)
                => new Attribute("ping", value);

            public static Attribute placeholder(string value)
                => new Attribute("placeholder", value);

            public static Attribute playsinline(string value)
                => new Attribute("playsinline", value);

            public static Attribute poster(string value)
                => new Attribute("poster", value);

            public static Attribute preload(string value)
                => new Attribute("preload", value);

            public static Attribute @readonly(string value)
                => new Attribute("readonly", value);

            public static Attribute referrerpolicy(string value)
                => new Attribute("referrerpolicy", value);

            public static Attribute rel(string value)
                => new Attribute("rel", value);

            public static Attribute required(string value)
                => new Attribute("required", value);

            public static Attribute reversed(string value)
                => new Attribute("reversed", value);

            public static Attribute rows(string value)
                => new Attribute("rows", value);

            public static Attribute rowspan(string value)
                => new Attribute("rowspan", value);

            public static Attribute sandbox(string value)
                => new Attribute("sandbox", value);

            public static Attribute scope(string value)
                => new Attribute("scope", value);

            public static Attribute selected(string value)
                => new Attribute("selected", value);

            public static Attribute shape(string value)
                => new Attribute("shape", value);

            public static Attribute size(string value)
                => new Attribute("size", value);

            public static Attribute sizes(string value)
                => new Attribute("sizes", value);

            public static Attribute slot(string value)
                => new Attribute("slot", value);

            public static Attribute span(string value)
                => new Attribute("span", value);

            public static Attribute spellcheck(string value)
                => new Attribute("spellcheck", value);

            public static Attribute src(string value)
                => new Attribute("src", value);

            public static Attribute srcdoc(string value)
                => new Attribute("srcdoc", value);

            public static Attribute srclang(string value)
                => new Attribute("srclang", value);

            public static Attribute srcset(string value)
                => new Attribute("srcset", value);

            public static Attribute start(string value)
                => new Attribute("start", value);

            public static Attribute step(string value)
                => new Attribute("step", value);

            public static Attribute style(string value)
                => new Attribute("style", value);

            public static Attribute tabindex(string value)
                => new Attribute("tabindex", value);

            public static Attribute target(string value)
                => new Attribute("target", value);

            public static Attribute title(string value)
                => new Attribute("title", value);

            public static Attribute translate(string value)
                => new Attribute("translate", value);

            public static Attribute type(string value)
                => new Attribute("type", value);

            public static Attribute usemap(string value)
                => new Attribute("usemap", value);

            public static Attribute value(string value)
                => new Attribute("value", value);

            public static Attribute width(string value)
                => new Attribute("width", value);

            public static Attribute wrap(string value)
                => new Attribute("wrap", value);
    }
}
