/* This file ist generated by the program DSLMethodsGenerator. DO NOT EDIT IT MANUALLY! */

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;
using System;

namespace BlazorDSL {
    static partial class Html {
        public static Attribute onFocus(object sender, Action<FocusEventArgs> callback)
            => new KeyValueAttribute(
                "onfocus",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onBlur(object sender, Action<FocusEventArgs> callback)
            => new KeyValueAttribute(
                "onblur",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onFocusIn(object sender, Action<FocusEventArgs> callback)
            => new KeyValueAttribute(
                "onfocusin",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onFocusOut(object sender, Action<FocusEventArgs> callback)
            => new KeyValueAttribute(
                "onfocusout",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onMouseOver(object sender, Action<MouseEventArgs> callback)
            => new KeyValueAttribute(
                "onmouseover",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onMouseOut(object sender, Action<MouseEventArgs> callback)
            => new KeyValueAttribute(
                "onmouseout",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onMouseMove(object sender, Action<MouseEventArgs> callback)
            => new KeyValueAttribute(
                "onmousemove",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onMouseDown(object sender, Action<MouseEventArgs> callback)
            => new KeyValueAttribute(
                "onmousedown",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onMouseUp(object sender, Action<MouseEventArgs> callback)
            => new KeyValueAttribute(
                "onmouseup",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onClick(object sender, Action<MouseEventArgs> callback)
            => new KeyValueAttribute(
                "onclick",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onDblClick(object sender, Action<MouseEventArgs> callback)
            => new KeyValueAttribute(
                "ondblclick",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onWheel(object sender, Action<WheelEventArgs> callback)
            => new KeyValueAttribute(
                "onwheel",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onMouseWheel(object sender, Action<WheelEventArgs> callback)
            => new KeyValueAttribute(
                "onmousewheel",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onContextMenu(object sender, Action<MouseEventArgs> callback)
            => new KeyValueAttribute(
                "oncontextmenu",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onDrag(object sender, Action<DragEventArgs> callback)
            => new KeyValueAttribute(
                "ondrag",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onDragEnd(object sender, Action<DragEventArgs> callback)
            => new KeyValueAttribute(
                "ondragend",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onDragEnter(object sender, Action<DragEventArgs> callback)
            => new KeyValueAttribute(
                "ondragenter",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onDragLeave(object sender, Action<DragEventArgs> callback)
            => new KeyValueAttribute(
                "ondragleave",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onDragOver(object sender, Action<DragEventArgs> callback)
            => new KeyValueAttribute(
                "ondragover",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onDragStart(object sender, Action<DragEventArgs> callback)
            => new KeyValueAttribute(
                "ondragstart",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onDrop(object sender, Action<DragEventArgs> callback)
            => new KeyValueAttribute(
                "ondrop",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onKeyDown(object sender, Action<KeyboardEventArgs> callback)
            => new KeyValueAttribute(
                "onkeydown",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onKeyUp(object sender, Action<KeyboardEventArgs> callback)
            => new KeyValueAttribute(
                "onkeyup",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onKeyPress(object sender, Action<KeyboardEventArgs> callback)
            => new KeyValueAttribute(
                "onkeypress",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onChange(object sender, Action<ChangeEventArgs> callback)
            => new KeyValueAttribute(
                "onchange",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onInput(object sender, Action<ChangeEventArgs> callback)
            => new KeyValueAttribute(
                "oninput",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onInvalid(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "oninvalid",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onReset(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onreset",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onSelect(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onselect",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onSelectStart(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onselectstart",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onSelectionChange(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onselectionchange",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onSubmit(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onsubmit",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onBeforeCopy(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onbeforecopy",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onBeforeCut(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onbeforecut",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onBeforePaste(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onbeforepaste",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onTouchCancel(object sender, Action<TouchEventArgs> callback)
            => new KeyValueAttribute(
                "ontouchcancel",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onTouchEnd(object sender, Action<TouchEventArgs> callback)
            => new KeyValueAttribute(
                "ontouchend",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onTouchMove(object sender, Action<TouchEventArgs> callback)
            => new KeyValueAttribute(
                "ontouchmove",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onTouchStart(object sender, Action<TouchEventArgs> callback)
            => new KeyValueAttribute(
                "ontouchstart",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onTouchEnter(object sender, Action<TouchEventArgs> callback)
            => new KeyValueAttribute(
                "ontouchenter",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onTouchLeave(object sender, Action<TouchEventArgs> callback)
            => new KeyValueAttribute(
                "ontouchleave",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onGotPointerCapture(object sender, Action<PointerEventArgs> callback)
            => new KeyValueAttribute(
                "ongotpointercapture",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onLostPointerCapture(object sender, Action<PointerEventArgs> callback)
            => new KeyValueAttribute(
                "onlostpointercapture",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onPointerCancel(object sender, Action<PointerEventArgs> callback)
            => new KeyValueAttribute(
                "onpointercancel",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onPointerDown(object sender, Action<PointerEventArgs> callback)
            => new KeyValueAttribute(
                "onpointerdown",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onPointerEnter(object sender, Action<PointerEventArgs> callback)
            => new KeyValueAttribute(
                "onpointerenter",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onPointerLeave(object sender, Action<PointerEventArgs> callback)
            => new KeyValueAttribute(
                "onpointerleave",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onPointerMove(object sender, Action<PointerEventArgs> callback)
            => new KeyValueAttribute(
                "onpointermove",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onPointerOut(object sender, Action<PointerEventArgs> callback)
            => new KeyValueAttribute(
                "onpointerout",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onPointerOver(object sender, Action<PointerEventArgs> callback)
            => new KeyValueAttribute(
                "onpointerover",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onPointerUp(object sender, Action<PointerEventArgs> callback)
            => new KeyValueAttribute(
                "onpointerup",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onCanPlay(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "oncanplay",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onCanPlayThrough(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "oncanplaythrough",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onCueChange(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "oncuechange",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onDurationChange(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "ondurationchange",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onEmptied(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onemptied",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onPause(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onpause",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onPlay(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onplay",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onPlaying(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onplaying",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onRateChange(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onratechange",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onSeeked(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onseeked",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onSeeking(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onseeking",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onStalled(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onstalled",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onStop(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onstop",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onSuspend(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onsuspend",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onTimeUpdate(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "ontimeupdate",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onVolumeChange(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onvolumechange",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onWaiting(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onwaiting",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onLoadStart(object sender, Action<ProgressEventArgs> callback)
            => new KeyValueAttribute(
                "onloadstart",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onTimeout(object sender, Action<ProgressEventArgs> callback)
            => new KeyValueAttribute(
                "ontimeout",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onAbort(object sender, Action<ProgressEventArgs> callback)
            => new KeyValueAttribute(
                "onabort",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onLoad(object sender, Action<ProgressEventArgs> callback)
            => new KeyValueAttribute(
                "onload",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onLoadend(object sender, Action<ProgressEventArgs> callback)
            => new KeyValueAttribute(
                "onloadend",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onProgress(object sender, Action<ProgressEventArgs> callback)
            => new KeyValueAttribute(
                "onprogress",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onError(object sender, Action<ErrorEventArgs> callback)
            => new KeyValueAttribute(
                "onerror",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onActivate(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onactivate",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onBeforeAtivate(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onbeforeactivate",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onBeforeDeactivate(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onbeforedeactivate",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onDeactivate(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "ondeactivate",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onEnded(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onended",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onFullScreenChange(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onfullscreenchange",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onFullScreenError(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onfullscreenerror",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onLoadedData(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onloadeddata",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onLoadedMetadata(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onloadedmetadata",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onPointerLockChange(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onpointerlockchange",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onPointerLockError(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onpointerlockerror",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onReadyStateChange(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onreadystatechange",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onScroll(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "onscroll",
                EventCallback.Factory.Create(sender, callback)
            );

        public static Attribute onToggle(object sender, Action<EventArgs> callback)
            => new KeyValueAttribute(
                "ontoggle",
                EventCallback.Factory.Create(sender, callback)
            );
    }
}
