/* This file ist generated by the program DSLMethodsGenerator. DO NOT EDIT IT MANUALLY! */

namespace BlazorDSL {
    public static partial class Html {
        
            public static Attribute abbr(string value)
                => new KeyValueAttribute("abbr", value);

            public static Attribute accept(string value)
                => new KeyValueAttribute("accept", value);

            public static Attribute acceptCharset(string value)
                => new KeyValueAttribute("accept-charset", value);

            public static Attribute accesskey(string value)
                => new KeyValueAttribute("accesskey", value);

            public static Attribute action(string value)
                => new KeyValueAttribute("action", value);

            public static Attribute allow(string value)
                => new KeyValueAttribute("allow", value);

            public static Attribute allowfullscreen(string value)
                => new KeyValueAttribute("allowfullscreen", value);

            public static Attribute alt(string value)
                => new KeyValueAttribute("alt", value);

            public static Attribute @as(string value)
                => new KeyValueAttribute("as", value);

            public static Attribute async(string value)
                => new KeyValueAttribute("async", value);

            public static Attribute autocapitalize(string value)
                => new KeyValueAttribute("autocapitalize", value);

            public static Attribute autocomplete(string value)
                => new KeyValueAttribute("autocomplete", value);

            public static Attribute autofocus(string value)
                => new KeyValueAttribute("autofocus", value);

            public static Attribute autoplay(string value)
                => new KeyValueAttribute("autoplay", value);

            public static Attribute charset(string value)
                => new KeyValueAttribute("charset", value);

            public static Attribute @checked(string value)
                => new KeyValueAttribute("checked", value);

            public static Attribute cite(string value)
                => new KeyValueAttribute("cite", value);

            public static Attribute className(string value)
                => new KeyValueAttribute("class", value);

            public static Attribute color(string value)
                => new KeyValueAttribute("color", value);

            public static Attribute cols(string value)
                => new KeyValueAttribute("cols", value);

            public static Attribute colspan(string value)
                => new KeyValueAttribute("colspan", value);

            public static Attribute content(string value)
                => new KeyValueAttribute("content", value);

            public static Attribute contenteditable(string value)
                => new KeyValueAttribute("contenteditable", value);

            public static Attribute controls(string value)
                => new KeyValueAttribute("controls", value);

            public static Attribute coords(string value)
                => new KeyValueAttribute("coords", value);

            public static Attribute crossorigin(string value)
                => new KeyValueAttribute("crossorigin", value);

            public static Attribute data(string value)
                => new KeyValueAttribute("data", value);

            public static Attribute datetime(string value)
                => new KeyValueAttribute("datetime", value);

            public static Attribute decoding(string value)
                => new KeyValueAttribute("decoding", value);

            public static Attribute @default(string value)
                => new KeyValueAttribute("default", value);

            public static Attribute defer(string value)
                => new KeyValueAttribute("defer", value);

            public static Attribute dir(string value)
                => new KeyValueAttribute("dir", value);

            public static Attribute dirname(string value)
                => new KeyValueAttribute("dirname", value);

            public static Attribute disabled(string value)
                => new KeyValueAttribute("disabled", value);

            public static Attribute download(string value)
                => new KeyValueAttribute("download", value);

            public static Attribute draggable(string value)
                => new KeyValueAttribute("draggable", value);

            public static Attribute enctype(string value)
                => new KeyValueAttribute("enctype", value);

            public static Attribute enterkeyhint(string value)
                => new KeyValueAttribute("enterkeyhint", value);

            public static Attribute @for(string value)
                => new KeyValueAttribute("for", value);

            public static Attribute form(string value)
                => new KeyValueAttribute("form", value);

            public static Attribute formaction(string value)
                => new KeyValueAttribute("formaction", value);

            public static Attribute formenctype(string value)
                => new KeyValueAttribute("formenctype", value);

            public static Attribute formmethod(string value)
                => new KeyValueAttribute("formmethod", value);

            public static Attribute formnovalidate(string value)
                => new KeyValueAttribute("formnovalidate", value);

            public static Attribute formtarget(string value)
                => new KeyValueAttribute("formtarget", value);

            public static Attribute headers(string value)
                => new KeyValueAttribute("headers", value);

            public static Attribute height(string value)
                => new KeyValueAttribute("height", value);

            public static Attribute hidden(string value)
                => new KeyValueAttribute("hidden", value);

            public static Attribute high(string value)
                => new KeyValueAttribute("high", value);

            public static Attribute href(string value)
                => new KeyValueAttribute("href", value);

            public static Attribute hreflang(string value)
                => new KeyValueAttribute("hreflang", value);

            public static Attribute httpEquiv(string value)
                => new KeyValueAttribute("http-equiv", value);

            public static Attribute id(string value)
                => new KeyValueAttribute("id", value);

            public static Attribute imagesizes(string value)
                => new KeyValueAttribute("imagesizes", value);

            public static Attribute imagesrcset(string value)
                => new KeyValueAttribute("imagesrcset", value);

            public static Attribute inputmode(string value)
                => new KeyValueAttribute("inputmode", value);

            public static Attribute integrity(string value)
                => new KeyValueAttribute("integrity", value);

            public static Attribute @is(string value)
                => new KeyValueAttribute("is", value);

            public static Attribute ismap(string value)
                => new KeyValueAttribute("ismap", value);

            public static Attribute itemid(string value)
                => new KeyValueAttribute("itemid", value);

            public static Attribute itemprop(string value)
                => new KeyValueAttribute("itemprop", value);

            public static Attribute itemref(string value)
                => new KeyValueAttribute("itemref", value);

            public static Attribute itemscope(string value)
                => new KeyValueAttribute("itemscope", value);

            public static Attribute itemtype(string value)
                => new KeyValueAttribute("itemtype", value);

            public static Attribute kind(string value)
                => new KeyValueAttribute("kind", value);

            public static Attribute label(string value)
                => new KeyValueAttribute("label", value);

            public static Attribute lang(string value)
                => new KeyValueAttribute("lang", value);

            public static Attribute list(string value)
                => new KeyValueAttribute("list", value);

            public static Attribute loading(string value)
                => new KeyValueAttribute("loading", value);

            public static Attribute loop(string value)
                => new KeyValueAttribute("loop", value);

            public static Attribute low(string value)
                => new KeyValueAttribute("low", value);

            public static Attribute max(string value)
                => new KeyValueAttribute("max", value);

            public static Attribute maxlength(string value)
                => new KeyValueAttribute("maxlength", value);

            public static Attribute media(string value)
                => new KeyValueAttribute("media", value);

            public static Attribute method(string value)
                => new KeyValueAttribute("method", value);

            public static Attribute min(string value)
                => new KeyValueAttribute("min", value);

            public static Attribute minlength(string value)
                => new KeyValueAttribute("minlength", value);

            public static Attribute multiple(string value)
                => new KeyValueAttribute("multiple", value);

            public static Attribute muted(string value)
                => new KeyValueAttribute("muted", value);

            public static Attribute name(string value)
                => new KeyValueAttribute("name", value);

            public static Attribute nomodule(string value)
                => new KeyValueAttribute("nomodule", value);

            public static Attribute nonce(string value)
                => new KeyValueAttribute("nonce", value);

            public static Attribute novalidate(string value)
                => new KeyValueAttribute("novalidate", value);

            public static Attribute open(string value)
                => new KeyValueAttribute("open", value);

            public static Attribute optimum(string value)
                => new KeyValueAttribute("optimum", value);

            public static Attribute pattern(string value)
                => new KeyValueAttribute("pattern", value);

            public static Attribute ping(string value)
                => new KeyValueAttribute("ping", value);

            public static Attribute placeholder(string value)
                => new KeyValueAttribute("placeholder", value);

            public static Attribute playsinline(string value)
                => new KeyValueAttribute("playsinline", value);

            public static Attribute poster(string value)
                => new KeyValueAttribute("poster", value);

            public static Attribute preload(string value)
                => new KeyValueAttribute("preload", value);

            public static Attribute @readonly(string value)
                => new KeyValueAttribute("readonly", value);

            public static Attribute referrerpolicy(string value)
                => new KeyValueAttribute("referrerpolicy", value);

            public static Attribute rel(string value)
                => new KeyValueAttribute("rel", value);

            public static Attribute required(string value)
                => new KeyValueAttribute("required", value);

            public static Attribute reversed(string value)
                => new KeyValueAttribute("reversed", value);

            public static Attribute rows(string value)
                => new KeyValueAttribute("rows", value);

            public static Attribute rowspan(string value)
                => new KeyValueAttribute("rowspan", value);

            public static Attribute sandbox(string value)
                => new KeyValueAttribute("sandbox", value);

            public static Attribute scope(string value)
                => new KeyValueAttribute("scope", value);

            public static Attribute selected(string value)
                => new KeyValueAttribute("selected", value);

            public static Attribute shape(string value)
                => new KeyValueAttribute("shape", value);

            public static Attribute size(string value)
                => new KeyValueAttribute("size", value);

            public static Attribute sizes(string value)
                => new KeyValueAttribute("sizes", value);

            public static Attribute slot(string value)
                => new KeyValueAttribute("slot", value);

            public static Attribute span(string value)
                => new KeyValueAttribute("span", value);

            public static Attribute spellcheck(string value)
                => new KeyValueAttribute("spellcheck", value);

            public static Attribute src(string value)
                => new KeyValueAttribute("src", value);

            public static Attribute srcdoc(string value)
                => new KeyValueAttribute("srcdoc", value);

            public static Attribute srclang(string value)
                => new KeyValueAttribute("srclang", value);

            public static Attribute srcset(string value)
                => new KeyValueAttribute("srcset", value);

            public static Attribute start(string value)
                => new KeyValueAttribute("start", value);

            public static Attribute step(string value)
                => new KeyValueAttribute("step", value);

            public static Attribute style(string value)
                => new KeyValueAttribute("style", value);

            public static Attribute tabindex(string value)
                => new KeyValueAttribute("tabindex", value);

            public static Attribute target(string value)
                => new KeyValueAttribute("target", value);

            public static Attribute title(string value)
                => new KeyValueAttribute("title", value);

            public static Attribute translate(string value)
                => new KeyValueAttribute("translate", value);

            public static Attribute type(string value)
                => new KeyValueAttribute("type", value);

            public static Attribute usemap(string value)
                => new KeyValueAttribute("usemap", value);

            public static Attribute value(string value)
                => new KeyValueAttribute("value", value);

            public static Attribute width(string value)
                => new KeyValueAttribute("width", value);

            public static Attribute wrap(string value)
                => new KeyValueAttribute("wrap", value);
    }
}
